### ISSUE TITLE
RangeError: index out of range:

### ISSUE THREAD

**Issue by zdary** [krissrex/google-authenticator-exporter#15]
node:readline:1252
            throw err;
            ^

RangeError: index out of range: 51 + 10 > 51
    at indexOutOfRange (C:\Users\test\google-authenticator-exporter\node_modules\protobufjs\src\reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (C:\Users\test\google-authenticator-exporter\node_modules\protobufjs\src\reader.js:98:19)
    at BufferReader.read_int32 [as int32] (C:\Users\test\google-authenticator-exporter\node_modules\protobufjs\src\reader.js:109:17)
    at Type.OtpParameters$decode [as decode] (eval at Codegen (C:\Users\test\google-authenticator-exporter\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:23:14)
    at Type.decode_setup [as decode] (C:\Users\test\google-authenticator-exporter\node_modules\protobufjs\src\type.js:507:25)
    at Type.MigrationPayload$decode [as decode] (eval at Codegen (C:\Users\test\google-authenticator-exporter\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:13:33)
    at Type.decode_setup [as decode] (C:\Users\test\google-authenticator-exporter\node_modules\protobufjs\src\type.js:507:25)
    at decodeProtobuf (C:\Users\test\google-authenticator-exporter\src\index.js:14:36)
    at decode (C:\Users\test\google-authenticator-exporter\src\index.js:48:19)
    at C:\Users\test\google-authenticator-exporter\src\index.js:176:22

**Comment by awehrung** [comment]
Experiencing a similar issue (using the docker setup):

```
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

RangeError: index out of range: 107 + 10 > 107
    at indexOutOfRange (/app/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (/app/node_modules/protobufjs/src/reader.js:98:19)
    at BufferReader.read_int32 [as int32] (/app/node_modules/protobufjs/src/reader.js:109:17)
    at Type.MigrationPayload$decode [as decode] (eval at Codegen (/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:25:15)
    at Type.decode_setup [as decode] (/app/node_modules/protobufjs/src/type.js:507:25)
    at decodeProtobuf (/app/src/index.js:14:36)
    at decode (/app/src/index.js:48:19)
    at /app/src/index.js:176:22
    at /app/node_modules/prompt/lib/prompt.js:357:32
    at /app/node_modules/async/lib/async.js:154:25

Node.js v17.7.2
```

and I have absolutely no idea how to debug this further :/

**Comment by krissrex** [comment]
I think this is related to #22.
What version of Authenticator do you use? 
I am unable to reproduce this fault myself, and I don't want you to send your secret code either...

**Comment by krissrex** [comment]
What QR decoder did you use? Does your uri end in a `%3D`, or in a `=`? I'm wondering if you copied the URI correctly from the QR.

**Comment by krissrex** [comment]
Does it still fail with the latest version of this repo?

**Comment by TimQuist** [comment]
Had the same issue. 

When I decoded the image with https://github.com/zxing/zxing it worked (online decoder hosted at [zxing.org](https://zxing.org/w/decode.jspx))

**Comment by krissrex** [comment]
> Had the same issue.
> 
> When I decoded the image with https://github.com/zxing/zxing it worked (online decoder hosted at [zxing.org](https://zxing.org/w/decode.jspx))

Nice catch. I suspect that whatever QR decoder was used, those with issues got only a part of the URI. The protobuf message was probably cut short.
